using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Phoney.SourceGenerator;

/// <summary>Writes the generated partial class: generator properties, model classes and their registration.</summary>
internal static class Emitter
{
    private const string Scope = "global::Phoney.Generation.FakeScope";

    /// <summary>Returns the source of the partial class for <paramref name="owner"/>.</summary>
    public static string Emit(INamedTypeSymbol owner, List<INamedTypeSymbol> roots, List<TypeModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>")
          .AppendLine("//   Generated by Phoney.SourceGenerator from [FakeFor<T>] attributes. Do not edit.")
          .AppendLine("// </auto-generated>")
          .AppendLine("#nullable disable")
          .AppendLine("#pragma warning disable")
          .AppendLine();

        var ns = owner.ContainingNamespace is { IsGlobalNamespace: false } n ? n.ToDisplayString() : null;
        if (ns is not null)
            sb.Append("namespace ").Append(ns).AppendLine(";").AppendLine();

        // Re-open the containing types, outermost first.
        var containers = new List<INamedTypeSymbol>();
        for (var t = owner; t is not null; t = t.ContainingType)
            containers.Insert(0, t);
        var indent = "";
        foreach (var container in containers)
        {
            sb.Append(indent).Append(container.IsStatic ? "static " : "").Append("partial ")
              .Append(container.IsRecord ? "record " : container.TypeKind == TypeKind.Struct ? "struct " : "class ")
              .AppendLine(container.Name);
            sb.Append(indent).AppendLine("{");
            indent += "    ";
        }

        var byFullName = models.ToDictionary(m => m.FullName);
        var usedNames = new HashSet<string>(owner.GetMembers().Select(m => m.Name));

        // One generator property per requested type.
        foreach (var root in roots)
        {
            var fullName = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!byFullName.TryGetValue(fullName, out var model))
                continue;
            var name = usedNames.Add(root.Name) ? root.Name : model.Key;
            sb.Append(indent).AppendLine($"/// <summary>A new generator for <see cref=\"{fullName}\"/> using the source-generated, reflection-free model.</summary>");
            sb.Append(indent).AppendLine($"public static global::Phoney.Generator<{fullName}> {name} => new(__phoneyModel_{model.Key});");
            sb.AppendLine();
        }

        foreach (var model in models)
            sb.Append(indent).AppendLine($"private static readonly __PhoneyModel_{model.Key} __phoneyModel_{model.Key} = new();");
        sb.AppendLine();

        // Registration makes Fake.For<T>() and nested objects use the generated models as well.
        if (CanRegister(owner))
        {
            sb.Append(indent).AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.Append(indent).AppendLine("internal static void __PhoneyRegisterModels()");
            sb.Append(indent).AppendLine("{");
            foreach (var model in models)
                sb.Append(indent).AppendLine($"    global::Phoney.Generation.ModelRegistry.Register(__phoneyModel_{model.Key});");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        foreach (var model in models)
            EmitModel(sb, indent, model);

        for (var i = containers.Count - 1; i >= 0; i--)
        {
            indent = indent.Substring(4);
            sb.Append(indent).AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>Module initializers must be reachable from the module: no private or protected containers.</summary>
    private static bool CanRegister(INamedTypeSymbol owner)
    {
        for (var t = owner; t is not null; t = t.ContainingType)
        {
            if (t.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                return false;
        }

        return true;
    }

    /// <summary>Writes one <c>FakeModel&lt;T&gt;</c> implementation: member table, <c>Create</c>, <c>Set</c> and init-only accessors.</summary>
    private static void EmitModel(StringBuilder sb, string indent, TypeModel model)
    {
        var i1 = indent + "    ";
        var i2 = i1 + "    ";
        var i3 = i2 + "    ";
        var t = model.FullName;
        sb.Append(indent).AppendLine($"private sealed class __PhoneyModel_{model.Key} : global::Phoney.Generation.FakeModel<{t}>");
        sb.Append(indent).AppendLine("{");

        // Validation rules from data annotations, one field per annotated member (declared before __members uses them).
        foreach (var m in model.Members.Where(m => m.Constraints is not null))
            sb.Append(i1).AppendLine($"private static readonly global::Phoney.Generation.MemberConstraints {m.ConstraintsField} = new() {{ {m.Constraints} }};");
        if (model.Members.Any(m => m.Constraints is not null))
            sb.AppendLine();

        // Member descriptions (index = position).
        sb.Append(i1).AppendLine("private static readonly global::Phoney.Generation.FakeMember[] __members =");
        sb.Append(i1).AppendLine("{");
        foreach (var m in model.Members)
        {
            sb.Append(i2).AppendLine(
                $"new global::Phoney.Generation.FakeMember(\"{m.Name}\", typeof({m.TypeName}), global::Phoney.Generation.ConventionKind.{m.Convention}, {Bool(m.IsConstructorParameter)}, {Bool(m.IsInitOnly)}, {m.ConstraintsField ?? "null"}),");
        }

        sb.Append(i1).AppendLine("};");
        sb.AppendLine();
        sb.Append(i1).AppendLine("public override global::System.Collections.Generic.IReadOnlyList<global::Phoney.Generation.FakeMember> Members => __members;");
        sb.AppendLine();

        // Create: values are produced in member order (constructor parameters, then members in declaration
        // order) exactly like the reflection model, so both consume randomness identically; then the object is
        // built with init/required members in its initializer and the rest assigned afterwards.
        sb.Append(i1).AppendLine($"public override {t} Create({Scope} scope)");
        sb.Append(i1).AppendLine("{");
        for (var index = 0; index < model.Members.Count; index++)
        {
            var m = model.Members[index];
            var value = m.IsConstructorParameter
                ? Get(index, m)
                : $"scope.Include({index}) ? {Get(index, m)} : default({m.TypeName})";
            sb.Append(i2).AppendLine($"var v{index} = {value};");
        }

        var arguments = model.Members
            .Select((m, index) => (m, index))
            .Where(x => x.m.IsConstructorParameter)
            .Select(x => "v" + x.index)
            .ToList();
        var initializers = model.Members
            .Select((m, index) => (m, index))
            .Where(x => !x.m.IsConstructorParameter && x.m.InInitializer)
            .ToList();
        sb.Append(i2).Append($"var o = new {t}(").Append(string.Join(", ", arguments)).Append(')');
        if (initializers.Count > 0)
        {
            sb.AppendLine();
            sb.Append(i2).AppendLine("{");
            foreach (var (m, index) in initializers)
                sb.Append(i3).AppendLine($"{m.Name} = v{index},");
            sb.Append(i2).Append('}');
        }

        sb.AppendLine(";");
        for (var index = 0; index < model.Members.Count; index++)
        {
            var m = model.Members[index];
            if (m.IsConstructorParameter || m.InInitializer)
                continue;
            sb.Append(i2).AppendLine($"if (scope.Include({index})) o.{m.Name} = v{index};");
        }

        sb.Append(i2).AppendLine("return o;");
        sb.Append(i1).AppendLine("}");
        sb.AppendLine();

        // Set: used for rules that depend on the created object.
        sb.Append(i1).AppendLine($"public override {t} Set({t} instance, int member, object value)");
        sb.Append(i1).AppendLine("{");
        sb.Append(i2).AppendLine("switch (member)");
        sb.Append(i2).AppendLine("{");
        for (var index = 0; index < model.Members.Count; index++)
        {
            var m = model.Members[index];
            if (m.IsConstructorParameter)
                continue;
            var assignment = m.IsInitOnly
                ? $"__set_{index}({(model.IsValueType ? "ref " : "")}instance, ({m.TypeName})value)"
                : $"instance.{m.Name} = ({m.TypeName})value";
            sb.Append(i3).AppendLine($"case {index}: {assignment}; return instance;");
        }

        sb.Append(i3).AppendLine("default: throw new global::System.InvalidOperationException(__members[member].Name + \" is a constructor parameter and cannot be set after creation.\");");
        sb.Append(i2).AppendLine("}");
        sb.Append(i1).AppendLine("}");

        // init-only setters are reachable after construction only through UnsafeAccessor (.NET 8+, AOT-safe).
        for (var index = 0; index < model.Members.Count; index++)
        {
            var m = model.Members[index];
            if (!m.IsInitOnly || m.IsConstructorParameter)
                continue;
            sb.AppendLine();
            sb.Append(i1).AppendLine($"[global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"set_{m.Name}\")]");
            sb.Append(i1).AppendLine($"private static extern void __set_{index}({(model.IsValueType ? "ref " : "")}{m.DeclaringType} target, {m.TypeName} value);");
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>The <c>scope.Get</c> call that reads member <paramref name="index"/> through the generator's rules.</summary>
    private static string Get(int index, MemberModel m) => $"scope.Get({index}, static s0 => {m.Value})";

    /// <summary>C# literal for a boolean.</summary>
    private static string Bool(bool value) => value ? "true" : "false";
}
