// <auto-generated>
//   Generated by Phoney.SourceGenerator from [FakeFor<T>] attributes. Do not edit.
// </auto-generated>
#nullable disable
#pragma warning disable

namespace Shop;

static partial class TestData
{
    /// <summary>A new generator for <see cref="global::Shop.Customer"/> using the source-generated, reflection-free model.</summary>
    public static global::Phoney.Generator<global::Shop.Customer> Customer => new(__phoneyModel_Shop_Customer);

    private static readonly __PhoneyModel_Shop_Customer __phoneyModel_Shop_Customer = new();
    private static readonly __PhoneyModel_Shop_Address __phoneyModel_Shop_Address = new();
    private static readonly __PhoneyModel_Shop_Order __phoneyModel_Shop_Order = new();

    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void __PhoneyRegisterModels()
    {
        global::Phoney.Generation.ModelRegistry.Register(__phoneyModel_Shop_Customer);
        global::Phoney.Generation.ModelRegistry.Register(__phoneyModel_Shop_Address);
        global::Phoney.Generation.ModelRegistry.Register(__phoneyModel_Shop_Order);
    }

    private sealed class __PhoneyModel_Shop_Customer : global::Phoney.Generation.FakeModel<global::Shop.Customer>
    {
        private static readonly global::Phoney.Generation.FakeMember[] __members =
        {
            new global::Phoney.Generation.FakeMember("Id", typeof(int), global::Phoney.Generation.ConventionKind.Id, false, false),
            new global::Phoney.Generation.FakeMember("FirstName", typeof(string), global::Phoney.Generation.ConventionKind.FirstName, false, false),
            new global::Phoney.Generation.FakeMember("Nickname", typeof(string), global::Phoney.Generation.ConventionKind.Username, false, false),
            new global::Phoney.Generation.FakeMember("Balance", typeof(decimal?), global::Phoney.Generation.ConventionKind.Price, false, false),
            new global::Phoney.Generation.FakeMember("Email", typeof(string), global::Phoney.Generation.ConventionKind.Email, false, true),
            new global::Phoney.Generation.FakeMember("Address", typeof(global::Shop.Address), global::Phoney.Generation.ConventionKind.None, false, true),
            new global::Phoney.Generation.FakeMember("Orders", typeof(global::System.Collections.Generic.List<global::Shop.Order>), global::Phoney.Generation.ConventionKind.None, false, false),
            new global::Phoney.Generation.FakeMember("Status", typeof(global::Shop.Status), global::Phoney.Generation.ConventionKind.None, false, false),
        };

        public override global::System.Collections.Generic.IReadOnlyList<global::Phoney.Generation.FakeMember> Members => __members;

        public override global::Shop.Customer Create(global::Phoney.Generation.FakeScope scope)
        {
            var v0 = scope.Include(0) ? scope.Get(0, static s0 => global::Phoney.Generation.ConventionValues.Number<int>(s0, global::Phoney.Generation.ConventionKind.Id)) : default(int);
            var v1 = scope.Include(1) ? scope.Get(1, static s0 => global::Phoney.Generation.ConventionValues.String(s0, global::Phoney.Generation.ConventionKind.FirstName)) : default(string);
            var v2 = scope.Include(2) ? scope.Get(2, static s0 => (s0.MaybeNull() ? null : global::Phoney.Generation.ConventionValues.String(s0, global::Phoney.Generation.ConventionKind.Username))) : default(string);
            var v3 = scope.Include(3) ? scope.Get(3, static s0 => (s0.MaybeNull() ? default(decimal?) : (decimal?)global::Phoney.Generation.ConventionValues.Number<decimal>(s0, global::Phoney.Generation.ConventionKind.Price))) : default(decimal?);
            var v4 = scope.Include(4) ? scope.Get(4, static s0 => global::Phoney.Generation.ConventionValues.String(s0, global::Phoney.Generation.ConventionKind.Email)) : default(string);
            var v5 = scope.Include(5) ? scope.Get(5, static s0 => s0.Nested<global::Shop.Address>()) : default(global::Shop.Address);
            var v6 = scope.Include(6) ? scope.Get(6, static s0 => s0.List<global::Shop.Order>(static s1 => s1.Nested<global::Shop.Order>())) : default(global::System.Collections.Generic.List<global::Shop.Order>);
            var v7 = scope.Include(7) ? scope.Get(7, static s0 => global::Phoney.Generation.ConventionValues.Enum<global::Shop.Status>(s0, global::Phoney.Generation.ConventionKind.None)) : default(global::Shop.Status);
            var o = new global::Shop.Customer()
            {
                Email = v4,
                Address = v5,
            };
            if (scope.Include(0)) o.Id = v0;
            if (scope.Include(1)) o.FirstName = v1;
            if (scope.Include(2)) o.Nickname = v2;
            if (scope.Include(3)) o.Balance = v3;
            if (scope.Include(6)) o.Orders = v6;
            if (scope.Include(7)) o.Status = v7;
            return o;
        }

        public override global::Shop.Customer Set(global::Shop.Customer instance, int member, object value)
        {
            switch (member)
            {
                case 0: instance.Id = (int)value; return instance;
                case 1: instance.FirstName = (string)value; return instance;
                case 2: instance.Nickname = (string)value; return instance;
                case 3: instance.Balance = (decimal?)value; return instance;
                case 4: __set_4(instance, (string)value); return instance;
                case 5: __set_5(instance, (global::Shop.Address)value); return instance;
                case 6: instance.Orders = (global::System.Collections.Generic.List<global::Shop.Order>)value; return instance;
                case 7: instance.Status = (global::Shop.Status)value; return instance;
                default: throw new global::System.InvalidOperationException(__members[member].Name + " is a constructor parameter and cannot be set after creation.");
            }
        }

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Email")]
        private static extern void __set_4(global::Shop.Customer target, string value);

        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = "set_Address")]
        private static extern void __set_5(global::Shop.Customer target, global::Shop.Address value);
    }

    private sealed class __PhoneyModel_Shop_Address : global::Phoney.Generation.FakeModel<global::Shop.Address>
    {
        private static readonly global::Phoney.Generation.FakeMember[] __members =
        {
            new global::Phoney.Generation.FakeMember("Street", typeof(string), global::Phoney.Generation.ConventionKind.StreetAddress, true, false),
            new global::Phoney.Generation.FakeMember("City", typeof(string), global::Phoney.Generation.ConventionKind.City, true, false),
        };

        public override global::System.Collections.Generic.IReadOnlyList<global::Phoney.Generation.FakeMember> Members => __members;

        public override global::Shop.Address Create(global::Phoney.Generation.FakeScope scope)
        {
            var v0 = scope.Get(0, static s0 => global::Phoney.Generation.ConventionValues.String(s0, global::Phoney.Generation.ConventionKind.StreetAddress));
            var v1 = scope.Get(1, static s0 => global::Phoney.Generation.ConventionValues.String(s0, global::Phoney.Generation.ConventionKind.City));
            var o = new global::Shop.Address(v0, v1);
            return o;
        }

        public override global::Shop.Address Set(global::Shop.Address instance, int member, object value)
        {
            switch (member)
            {
                default: throw new global::System.InvalidOperationException(__members[member].Name + " is a constructor parameter and cannot be set after creation.");
            }
        }
    }

    private sealed class __PhoneyModel_Shop_Order : global::Phoney.Generation.FakeModel<global::Shop.Order>
    {
        private static readonly global::Phoney.Generation.FakeMember[] __members =
        {
            new global::Phoney.Generation.FakeMember("Id", typeof(global::System.Guid), global::Phoney.Generation.ConventionKind.Id, true, false),
            new global::Phoney.Generation.FakeMember("CreatedAt", typeof(global::System.DateTime), global::Phoney.Generation.ConventionKind.PastDate, true, false),
            new global::Phoney.Generation.FakeMember("Customer", typeof(global::Shop.Customer), global::Phoney.Generation.ConventionKind.None, false, false),
        };

        public override global::System.Collections.Generic.IReadOnlyList<global::Phoney.Generation.FakeMember> Members => __members;

        public override global::Shop.Order Create(global::Phoney.Generation.FakeScope scope)
        {
            var v0 = scope.Get(0, static s0 => global::Phoney.Generation.ConventionValues.Guid(s0, global::Phoney.Generation.ConventionKind.Id));
            var v1 = scope.Get(1, static s0 => global::Phoney.Generation.ConventionValues.DateTime(s0, global::Phoney.Generation.ConventionKind.PastDate));
            var v2 = scope.Include(2) ? scope.Get(2, static s0 => (s0.MaybeNull() ? null : s0.Nested<global::Shop.Customer>())) : default(global::Shop.Customer);
            var o = new global::Shop.Order(v0, v1);
            if (scope.Include(2)) o.Customer = v2;
            return o;
        }

        public override global::Shop.Order Set(global::Shop.Order instance, int member, object value)
        {
            switch (member)
            {
                case 2: instance.Customer = (global::Shop.Customer)value; return instance;
                default: throw new global::System.InvalidOperationException(__members[member].Name + " is a constructor parameter and cannot be set after creation.");
            }
        }
    }

}
