using System.Text;

namespace Phoney.DataCompiler;

/// <summary>Emits the generated C# that the runtime compiles together with the binary locale resources.</summary>
internal static class CodeEmitter
{
    private const string Header = """
        // <auto-generated>
        //   Generated by tools/Phoney.DataCompiler from faker.js locale data. Do not edit by hand.
        // </auto-generated>
        #nullable enable

        """;

    /// <summary>Generates <c>DataKeys.g.cs</c>: one constant per key, paths and group ids.</summary>
    public static string DataKeys(Catalog catalog)
    {
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        var sb = new StringBuilder(Header);
        sb.AppendLine("namespace Phoney.Data;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Integer ids of every locale data key, indexing <see cref=\"LocaleData\"/> entries.</summary>");
        sb.AppendLine("internal static class DataKeys");
        sb.AppendLine("{");
        sb.AppendLine($"    public const int Count = {catalog.Keys.Count};");
        sb.AppendLine();
        for (var i = 0; i < catalog.Keys.Count; i++)
        {
            var name = Identifier(catalog.Keys[i]);
            if (!names.TryAdd(name, catalog.Keys[i]))
                throw new InvalidDataException($"Keys '{names[name]}' and '{catalog.Keys[i]}' both map to identifier '{name}'.");
            sb.AppendLine($"    /// <summary><c>{catalog.Keys[i]}</c> ({catalog.KindOfKey[i]})</summary>");
            sb.AppendLine($"    public const int {name} = {i};");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Dotted path of each key, indexed by key id.</summary>");
        sb.AppendLine("    public static readonly string[] Paths =");
        sb.AppendLine("    [");
        foreach (var key in catalog.Keys)
            sb.AppendLine($"        {Literal(key)},");
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Entry group (faker.js <c>module.entry</c>) of each key; fallback resolution happens per group.</summary>");
        sb.AppendLine($"    public static ReadOnlySpan<ushort> GroupOf => [{string.Join(", ", catalog.GroupOfKey)}];");
        sb.AppendLine();
        sb.AppendLine($"    public const int GroupCount = {catalog.Groups.Count};");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Generates <c>LocaleCatalog.g.cs</c>: locale metadata, fallback chains and referenced template methods.</summary>
    public static string LocaleCatalog(string fakerVersion, IReadOnlyList<RawLocale> locales, IEnumerable<string> methodReferences)
    {
        var sb = new StringBuilder(Header);
        sb.AppendLine("namespace Phoney.Data;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class LocaleCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The faker.js version the embedded locale data was imported from.</summary>");
        sb.AppendLine($"    public const string FakerVersion = {Literal(fakerVersion)};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>All embedded locales.</summary>");
        sb.AppendLine("    public static readonly LocaleInfo[] Embedded =");
        sb.AppendLine("    [");
        foreach (var l in locales)
        {
            string M(string key) => l.Metadata.TryGetValue(key, out var v) ? Literal(v) : "null";
            var fallback = string.Join(", ", l.Fallback.Select(Literal));
            sb.AppendLine($"        new({Literal(l.Code)}, {M("title")}, {M("endonym")}, {M("language")}, {M("country")}, {M("script")}, {M("dir")}, [{fallback}]),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>faker.js methods referenced from <c>{{...}}</c> templates in the locale data; each must be registered in <see cref=\"Phoney.Templates.TemplateFunctions\"/>.</summary>");
        sb.AppendLine("    public static readonly string[] TemplateMethodReferences =");
        sb.AppendLine("    [");
        foreach (var method in methodReferences)
            sb.AppendLine($"        {Literal(method)},");
        sb.AppendLine("    ];");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Markdown table of the usable locales (everything except <c>base</c>, which only holds shared data) for the
    /// README, so the documented list always matches the embedded data.
    /// </summary>
    public static string LocaleTable(string fakerVersion, IReadOnlyList<RawLocale> locales)
    {
        var usable = locales.Where(l => l.Code != "base").ToList();
        var sb = new StringBuilder();
        sb.AppendLine($"{usable.Count} locales from faker.js {fakerVersion}. Codes accept `-` or `_` and any casing (`de-AT`, `de_at`). .NET culture names resolve to the closest locale, including script-tagged ones (`sv-SE` → `sv`, `sr-Latn-RS` → `sr_RS_latin`, `zh-Hant-TW` → `zh_TW`, `ckb-IQ` → `ku_ckb`); a requested script is never substituted.");
        sb.AppendLine();
        sb.AppendLine("| Code | Language | Native name | Falls back to |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var l in usable)
        {
            string M(string key) => l.Metadata.TryGetValue(key, out var v) ? v.Replace("|", "\\|", StringComparison.Ordinal) : "";
            var fallback = string.Join(" → ", l.Fallback.Where(f => f != "base")) is { Length: > 0 } chain ? chain : "—";
            sb.AppendLine($"| `{l.Code}` | {M("title")} | {M("endonym")} | {fallback} |");
        }

        return sb.ToString();
    }

    /// <summary>Converts <c>person.first_name.female</c> into <c>PersonFirstNameFemale</c>.</summary>
    public static string Identifier(string path)
    {
        var sb = new StringBuilder();
        foreach (var segment in path.Split('.'))
        {
            foreach (var part in segment.Split('_', '-', ' '))
            {
                if (part.Length == 0)
                    continue;
                var clean = new string(part.Where(char.IsAsciiLetterOrDigit).ToArray());
                if (clean.Length == 0)
                    continue;
                sb.Append(char.ToUpperInvariant(clean[0])).Append(clean.AsSpan(1));
            }
        }

        if (sb.Length == 0 || char.IsAsciiDigit(sb[0]))
            sb.Insert(0, '_');
        return sb.ToString();
    }

    /// <summary>A C# string literal for <paramref name="value"/>.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (char.IsControl(c))
                        sb.Append($"\\u{(int)c:x4}");
                    else
                        sb.Append(c);
                    break;
            }
        }

        return sb.Append('"').ToString();
    }
}
